### ISSUE TITLE
Compiling C Programs

### ISSUE THREAD

**Issue by imcnanie** [parhansson/KMotionX#10]
Hello,

I am not able to use KMotionX to compile C Programs, so I still have to use a separate windows computer to initialize my KStep. Is compiling supported? I've been working with the test example program. Here is the relevant code:

`void testCompile(){
        char file[256];
	//strcpy(file,kmx::getInstallPath());
	strcpy(file,[PATH TO BlinkKFLOP.c]);
	//strcat(file,"/C Programs/FanOFF.c");
	char err[1024];
	KM->CompileAndLoadCoff(file, 1, err, sizeof(err));
	//KM->CompileAndLoadCoff(file, 1);
	if(err[0])
	{
	  printf("error %s", err);
	}
	else {
	  printf(compiled %s", file);
	}
}`

Thank you!

**Comment by parhansson** [comment]
Yes compiling is supported. However there was a bug in resolving the path of the compiler.
I must admit I have not executed the examples for a while. 

Pull the latest from master and "make install"  again. I have updated the test example with your fixes. 

It is nice to see that someone actually uses the code.

**Comment by imcnanie** [comment]
Thank you for your work! It's useful!

Just recloned the repo to test. Still doesn't seem to be compiling on ubuntu 18.04. I get the following output, running ./testRunner. I removed the tests other than the testCompile() function:

[INFO] (KMotionX.cpp:119) Using KMOTIONX_HOME=/home/golfbot/.kmotionx
[INFO] (KMotionX.cpp:148) Launching KMotionServer: '/home/golfbot/.kmotionx/bin/KMotionServer &'
CheckForReady succeded
[INFO] (KmotionIOX.cpp:670) ftdi_get_latency_timer old value 16
CheckKMotionVersion Succeeded
Location[0] Board nr: 0
USB Location: 0
---------AfxMessageBox:  (0x00051010)  ---------
tcc: Unable to open output file

-----------------------------------------------
>OK?
---------AfxMessageBox:  (0x00051010)  ---------
/home/golfbot/.kmotionx/bin/tcc67 -text 80050000 -g -nostdinc -I"/home/golfbot/.kmotionx/DSP_KFLOP" -I"/home/golfbot/.kmotionx/C Programs" -o "/home/golfbot/.kmotionx/C Programs/BlinkKFLOP(1).out" "/home/golfbot/.kmotionx/C Programs/BlinkKFLOP.c" "/home/golfbot/.kmotionx/DSP_KFLOP/DSPKFLOP.out" 2>&1
-----------------------------------------------
>OK?
tcc: Unable to open output file

[INFO] (KMotionLocal.cpp:64) share = 2
[INFO] (KMotionLocal.cpp:75) To reset shared memory launch server with reset option 'KMotionServer -reset'

**Comment by parhansson** [comment]
This is a problem due to executing "make install" with sudo, which is required on linux.

The problem is that root is owner of ~/.kmotionx directory tree, and the testRunner binary is executed by a another user.

Normally this would not be a problem since only reads are made. But now, the testRunner is compiling a file and tries to write into the directory (~/.kmotionx/C\ programs/BlinkKLFOP.out)

You can resolve this by taking ownership of that directory structure
`sudo chown -R <your_user_name> ~/.kmotion`

I'm on MacOS and do not always test thing on every platform. Sorry for the inconvenience.

I have not managed to create install packages for different platforms.

**Comment by imcnanie** [comment]
Okay, I just tried that, but it still doesn't seem to blink the LEDs on the KFLOP. Is there another command to actually run the compiled program?

**Comment by imcnanie** [comment]
Figured out a solution, I can run the following code to start the thread after I upload it:

testCompile();
if (KM->WriteLine( "Execute1"))	MyError();

Thanks again for your work on this library!
